const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function allowedHost(host){const h=String(host||"").toLowerCase();return h==="maps.app.goo.gl"||h==="goo.gl"||h==="google.com"||h==="www.google.com"||h==="maps.google.com"||h.endsWith(".google.com")||/^www\.google\.[a-z.]+$/.test(h)||/^maps\.google\.[a-z.]+$/.test(h)}
function coords(text){let t=String(text||"").replace(/&amp;/g,"&");try{t=decodeURIComponent(t)}catch(e){}const patterns=[/@(-?\d{1,2}(?:\.\d+)?),(-?\d{1,3}(?:\.\d+)?)/i,/!3d(-?\d{1,2}(?:\.\d+)?)!4d(-?\d{1,3}(?:\.\d+)?)/i,/(?:query|q|destination|ll|center|daddr)=(-?\d{1,2}(?:\.\d+)?)[,%2C\s]+(-?\d{1,3}(?:\.\d+)?)/i,/\/(-?\d{1,2}(?:\.\d+)?),(-?\d{1,3}(?:\.\d+)?)(?:[/?]|$)/];for(const re of patterns){const m=t.match(re);if(!m)continue;const lat=Number(m[1]),lng=Number(m[2]);if(Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180)return{lat,lng}}return null}
export default{async fetch(request){
 if(request.method==="OPTIONS")return new Response(null,{headers:CORS});if(request.method!=="GET")return json({ok:false,error:"Method not allowed"},405);
 const incoming=new URL(request.url);if(incoming.searchParams.get("ping")==="1")return json({ok:true,service:"OLMS Maps Resolver",version:"1.0"});
 const raw=incoming.searchParams.get("url")||"";let target;try{target=new URL(raw)}catch(e){return json({ok:false,error:"URL inválida"},400)}if(!allowedHost(target.hostname))return json({ok:false,error:"Solo se aceptan enlaces de Google Maps"},400);
 try{const response=await fetch(target.toString(),{method:"GET",redirect:"follow",headers:{"User-Agent":"Mozilla/5.0 (compatible; OLMSMapsResolver/1.0)","Accept":"text/html,application/xhtml+xml"}});const finalUrl=response.url||target.toString();let point=coords(finalUrl);if(!point){const location=response.headers.get("location");if(location)point=coords(new URL(location,finalUrl).toString())}return json({ok:true,finalUrl,...(point||{})});}catch(e){return json({ok:false,error:"No se pudo resolver el enlace"},502)}
}};
